### ISSUE TITLE
VDOM: Mount/Render

### ISSUE THREAD

**Issue by jimfranke** [iosio/iosio#1]
Cool how you combine Superfine with native Web Components! Can you please explain how you use the "mount" function in combination with the "render" function? I'm interested since i'd like to render directly to the shadowroot without a wrapping element.

**Comment by iosio** [comment]
Hey thanks, been messing with a few different vdom approaches. (btw, I will probably move this to another package/repo. will link it here once I do). I had wrestled with superfine for a hot minute, trying to get it to render into a shadow root, but found a work around (shown in the render function), however the workaround will overwrite everything in the document tree. Works great for a web component, but if you want to render off of document.body without overwriting any existing script tags, you can use mount. 

Not sure if you've seen this post by @developit, but he wrote a vdom lib almost as small as a tweet.
https://twitter.com/_developit/status/1232891191110389760 

What I like about it over superfine is that it has a hook-like update function as a third argument in a functional component, but its not totally perfect when working with fragments. Will be pushing up a version of that with some alterations I made next time I push as well. 

Also, you can check out the CSS property, "display:contents". It's basically makes an element behave almost like a document fragment. You could actually use that on the first node (wrapping element) to render into when using superfine out-of-box.

**Comment by jimfranke** [comment]
Thanks for your tips! I'm looking forward to your altered version of tweet sized vdom with better fragment support! When do you expect to push it?

**Comment by iosio** [comment]
@jimfranke No fragments yet but I posted a link to a the forked gist here. https://gist.github.com/developit/2038b141b31287faa663f410b6649a87#gistcomment-3216093

**Comment by jimfranke** [comment]
> I had wrestled with superfine for a hot minute, trying to get it to render into a shadow root, but found a work around (shown in the render function), however the workaround will overwrite everything in the document tree. Works great for a web component, but if you want to render off of document.body without overwriting any existing script tags, you can use mount.

What do you mean by overwriting the entire tree? Is hydration of existing nodes via recycleNode no longer working?

**Comment by iosio** [comment]
So like, if you are mounting to document.body, and inside of document body you have existing script tags as children of the body element, they will be removed and replaced with what you want to render using the render function. Its easily avoidable if you append an element to the body and then use that as render mounting point, rather than the body element itself, avoiding any adjacent elements. I think react actually suggests doing it that way anyway.  I haven't messed with any of the recycleNode functionality. Just upgraded props diffing and, enabled the use of fragments.

I finally got around to creating a dedicated repo and npm module for it here [superfinesse](https://github.com/iosio/superfinesse)
